<?php

/**
 * @file
 * Language logic for various aspects on the site.
 */

declare(strict_types = 1);

use Drupal\Core\Language\Language;
use Drupal\Core\Url;

/**
 * Implements hook_module_implements_alter().
 */
function ecms_languages_module_implements_alter(&$implementations, $hook) {
  if (isset($implementations['hook'])) {
    $group = $implementations['hook'];
    unset($implementations['hook']);
    $implementations['hook'] = $group;
  }
}

/**
 * Implements hook_language_switch_links_alter().
 *
 * We need to filter out the languages from the configuration list.
 */
function ecms_languages_language_switch_links_alter(array &$links, string $type, Url $path) : void {

  $config = \Drupal::config('ecms_languages.settings');
  $excluded_languages = $config->get('excluded_languages') ?? [];

  if (empty($excluded_languages)) {
    return;
  }

  // Remove languages that were flagged in the configuration.
  foreach ($links as $langcode => $link) {
    // If the language was checked, remove it.
    if ($excluded_languages[$langcode] === $langcode) {
      unset($links[$langcode]);
    }
  }
}

/**
 * Implements hook_language_negotiation_info_alter().
 *
 * We need to update the session negotiator to fix translation
 * links in the admin.
 */
function ecms_languages_language_negotiation_info_alter(array &$negotiation_info): void {
  $negotiation_info['language-session']['class'] = 'Drupal\ecms_languages\LanguageNegotiationSessionFix';
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function ecms_languages_pathauto_alias_alter(&$alias, array &$context): void {
  // Force all aliases to be saved as language neutral.
  $context['language'] = Language::LANGCODE_NOT_SPECIFIED;
}
