<?php

/**
 * @file
 * Language logic for various aspects on the site.
 */

declare(strict_types = 1);

use Drupal\Core\Url;

/**
 * Implements hook_language_switch_links_alter().
 *
 * We need to filter out the languages from the configuration list.
 */
function ecms_languages_language_switch_links_alter(array &$links, string $type, Url $path) : void {

  $config = \Drupal::config('ecms_languages.settings');
  $excluded_languages = $config->get('excluded_languages') ?? [];

  if (empty($excluded_languages)) {
    return;
  }

  // Remove languages that were flagged in the configuration.
  foreach ($links as $langcode => $link) {
    // If the language was checked, remove it.
    if ($excluded_languages[$langcode] === $langcode) {
      unset($links[$langcode]);
    }
  }
}

/**
 * Implements hook_language_negotiation_info_alter().
 *
 * We need to update the session negotiator to fix translation
 * links in the admin.
 */
function ecms_languages_language_negotiation_info_alter(array &$negotiation_info) {
  $negotiation_info['language-session']['class'] = 'Drupal\ecms_languages\LanguageNegotiationSessionFix';
}
