<?php

/**
 * @file
 * Language logic for various aspects on the site.
 */

declare(strict_types = 1);

use Drupal\Core\Language\Language;
use Drupal\Core\Url;

/**
 * Implements hook_module_implements_alter().
 */
function ecms_languages_module_implements_alter(&$implementations, $hook) {
  if (isset($implementations['hook'])) {
    $group = $implementations['hook'];
    unset($implementations['hook']);
    $implementations['hook'] = $group;
  }
}

/**
 * Implements hook_language_switch_links_alter().
 *
 * We need to filter out the languages from the configuration list.
 */
function ecms_languages_language_switch_links_alter(array &$links, string $type, Url $path) : void {

  $config = \Drupal::config('ecms_languages.settings');
  $excluded_languages = $config->get('excluded_languages') ?? [];

  if (empty($excluded_languages)) {
    return;
  }

  // Remove languages that were flagged in the configuration.
  foreach ($links as $langcode => $link) {
    // If the language was checked, remove it.
    if ($excluded_languages[$langcode] === $langcode) {
      unset($links[$langcode]);
    }
  }
}

/**
 * Implements hook_language_negotiation_info_alter().
 *
 * We need to update the session negotiator to fix translation
 * links in the admin.
 */
function ecms_languages_language_negotiation_info_alter(array &$negotiation_info): void {
  $negotiation_info['language-session']['class'] = 'Drupal\ecms_languages\LanguageNegotiationSessionFix';
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function ecms_languages_pathauto_alias_alter(&$alias, array &$context): void {
  // Force all aliases to be saved as language neutral.
  $context['language'] = Language::LANGCODE_NOT_SPECIFIED;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function ecms_languages_menu_local_tasks_alter(array &$data, ?string $route_name): void {
  if ($route_name === NULL) {
    return;
  }

  // Remove the toggle publish tabs for node view and edit routes.
  if ($route_name === 'entity.node.canonical'
    || $route_name === 'entity.node.edit_form') {

    // Hide the "Publish" / "Unpublish" tabs since they do not work
    // with content moderation.
    if (!empty($data['tabs'][0]['entity.node.publish'])) {
      unset($data['tabs'][0]['entity.node.publish']);
    }
    if (!empty($data['tabs'][0]['entity.node.publish_translation'])) {
      unset($data['tabs'][0]['entity.node.publish_translation']);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ecms_languages_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage(print_r($form_id, TRUE), 'info');
}
