name: eCMS Search Settings
description: 'Provides a config form to set character count in search results on site by site basis.'
type: module
core_version_requirement: ^9
package: eCMS
dependencies: {  }
