ecms_languages.settings:
  type: config_object
  mapping:
    excluded_languages:
      type: sequence
        label: 'Excluded Languages'
        sequence:
          type: string
          label: 'Langcode'
