<?php

/**
 * @file
 * ecms_covid_publication_migrate.install
 */

declare(strict_types=1);

use Drupal\Core\Config\FileStorage;
use Drupal\Core\Database\Database;

/**
 * Update existing Covid publication import configuration.
 */
function ecms_covid_publication_migrate_update_9000(array $sandbox): void {
  // Add the sourceid2 to the migrate_map table.
  $sourceId2Column = [
    'type' => 'varchar',
    'description' => 'sourceid2',
    'length' => 255,
    'not null' => FALSE,
  ];

  $schema = Database::getConnection()->schema();
  $schema->addField('migrate_map_ecms_covid_publication_types', 'sourceid2', $sourceId2Column);
  $schema->addField('migrate_map_ecms_covid_publications_rss', 'sourceid2', $sourceId2Column);

  // Config updates.
  $path = \Drupal::service('extension.list.module')->getPath('ecms_covid_publication_migrate');

  /** @var \Drupal\Core\Config\FileStorage $install_source */
  $install_source = new FileStorage($path . "/config/install/");

  /** @var \Drupal\Core\Config\StorageInterface $active_storage */
  $active_storage = \Drupal::service('config.storage');

  $newConfig = [
    'migrate_plus.migration.ecms_covid_publication_types',
    'migrate_plus.migration.ecms_covid_publications_rss',
  ];

  foreach ($newConfig as $config) {
    $active_storage->write("{$config}", $install_source->read("{$config}"));
  }
}
