<?php

/**
 * @file
 * ecms_workflow.module
 */

declare(strict_types = 1);

use Drupal\node\Entity\Node;
use Drupal\webform\WebformInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ecms_workflow_webform_insert(WebformInterface $webform) : void {
  $node = Node::create([
    'type' => 'webform',
    'title' => $webform->label(),
    'webform' => ['target_id' => $webform->id()],
  ]);
  $node->save();

  \Drupal::messenger()->addMessage(t('Webform node %label created.', ['%label' => $node->label()]));
}
