ecms_api_publisher.settings:
  type: config_object
  mapping:
    oauth_client_id:
      type: string
      label: 'OAuth Client ID'
    oauth_client_secret:
      type: string
      label: 'OAuth Client secret'
    api_publisher_mail:
      type: string
      label: 'Publisher user email address'
