name: eCMS Google Translate
type: eCMS
description: 'Configures Google Translate module for eCMS with custom settings and block placement'
install:
  - gtranslate

config:
  strict: false
  import:
    block:
      - block.block.gtranslate_block
      - block.block.ecms_ecmstranslatorgoogletranslator
