name: eCMS Google Translate
type: eCMS
description: 'Configures Google Translate module for eCMS with custom settings and block placement'
install:
  - gtranslate

config:
  strict: false
  actions:
  import:
    - ecms_base/recipes/ecms_gtranslate/content/block/block.block.gtranslate_block.yml
