<?php

declare(strict_types = 1);

namespace Drupal\ecms_search_settings\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Provide config form to set custom search settings, e.g. character count.
 *
 * @package Drupal\ecms_search_settings\Form
 */
class EcmsSearchSettingsConfigForm extends ConfigFormBase {

  /**
   * {@inheritDoc}
   */
  protected function getEditableConfigNames(): array {
    return [
      'ecms_search_settings.settings',
    ];
  }

  /**
   * {@inheritDoc}
   */
  public function getFormId(): string {
    return 'ecms_search_settings_form';
  }

  /**
   * {@inheritDoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state): array {
    $form = parent::buildForm($form, $form_state);

    $search_settings_config = $this->config('ecms_search_settings.settings');
    if (isset($search_settings_config)) {
      $current_excerpt_length = $search_settings_config->get('excerpt_length');
      $current_character_limit = $search_settings_config->get('character_limit');
    }

    $form['excerpt_length'] = [
      '#title' => $this->t(
        'Length of Highlight excerpt in Search Index config'
      ),
      '#description' => $this->t(
        'Set the length of the excerpt generated by the Highlight processor of Search API index, to handle search results with long text. Defaults to 256.'
      ),
      '#type' => 'textfield',
      '#default_value' => $current_excerpt_length ?? '256',
    ];

    $form['character_limit'] = [
      '#title' => $this->t('Character Limit in Search Results template'),
      '#description' => $this->t(
        'Set the limit of characters in search results with long text, truncating the excerpt before rendering it. Defaults to 190.'
      ),
      '#type' => 'textfield',
      '#default_value' => $current_character_limit ?? '190',
    ];

    return $form;
  }

  /**
   * {@inheritDoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state): void {
    parent::submitForm($form, $form_state);

    $excerpt_length = $form_state->getValue('excerpt_length');
    $character_limit = $form_state->getValue('character_limit');

    // Store value in this module's config settings.
    $this->config('ecms_search_settings.settings')
      ->set('excerpt_length', $excerpt_length)
      ->set('character_limit', $character_limit)
      ->save();

    // Set excerpt length in config for search index's 'highlighter' processor.
    $config = \Drupal::service('config.factory')
      ->getEditable('search_api.index.acquia_search_index');
    $config->set('processor_settings.highlight.excerpt_length', $character_count)
      ->save();
  }

}
