<?php

/**
 * @file
 * ecms_migration.module
 */

declare(strict_types=1);

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for the ecms_file_redirect migration.
 */
function ecms_migration_migrate_ecms_file_redirect_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration): void {
  // Ensure we have the right public files directory for the current site.
  /** @var \Drupal\Core\File\FileUrlGeneratorInterface $fileUrlGenerator */
  $fileUrlGenerator = \Drupal::service('file_url_generator');
  $public_file_path = rtrim($fileUrlGenerator->transformRelative($fileUrlGenerator->generateAbsoluteString('public://')), "/");

  // Make sure this is a valid internal Uri.
  $public_file_path = "internal:{$public_file_path}";

  // Replace the DRUPAL_FILE_DIRECTORY constant with the site specific value.
  $row
    ->setSourceProperty('constants/DRUPAL_FILE_DIRECTORY', $public_file_path);
}
