<?php

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\Core\Site\Settings;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for the ecms_file_redirect migration.
 */
function ecms_migration_migrate_ecms_file_redirect_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // Load the $settings['file_public_path'];
  // This is required as every site within ACSF will have a different path.
  $public_file_path = Settings::get('file_public_path');

  $row
    ->setSourceProperty('constants/DRUPAL_FILE_DIRECTORY', "internal:/{$public_file_path}");
}
