# Runs and tests the develop.sh script
---
name: Test the Ecms Profile
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: develop.sh
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache the vendor directory
        id: drupal-cache
        run: |
            echo "::set-output name=dir::../develop-ecms-profile/vendor"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.drupal-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      - name: Run the develop CI script.
        run: ./scripts/develop-ci.sh
        if: steps.drupal-cache.outputs.cache-hit != 'true'

      - name: Check coding standards.
        run: |
          cd ../develop-ecms-profile
          ./vendor/bin/phpcs --standard=../ecms_profile/phpcs.xml

      - name: Run unit tests.
        run: |
          cd ../develop-ecms-profile
          ./vendor/bin/phpunit --configuration=../ecms_profile/phpunit-ci.xml --testsuite=unit

      - name: Install the site.
        run: |
          cd ../develop-ecms-profile
          ./vendor/bin/drush si --db-url=sqlite://web/.ht.sqlite

      - name: Run functional tests.
        run: |
          cd ../develop-ecms-profile
          ./vendor/bin/phpunit --configuration=../ecms_profile/phpunit-ci.xml --testsuite=functional

#      - name: Prepare environment for Lando use
#        run: |
#          mkdir -p ~/.ssh
#
#      - name: Install Lando
#        run: |
#          pushd /tmp
#          wget https://files.devwithlando.io/lando-stable.deb
#          sudo dpkg -i --ignore-depends=docker-ce lando-stable.deb
#          popd
#
#      - name: Print directory.
#        run: |
#          pwd
#
##      - name: Cache the lando environment
##        id: lando-cache
##        run: |
##            echo "::set-output name=dir::/home/runner/work/ecms_profile/develop-ecms-profile"
##
##      - uses: actions/cache@v2
##        with:
##          path: ${{ steps.lando-cache.outputs.dir }}
##          key: ${{ runner.os }}-composer-${{ hashFiles('/home/runner/work/ecms_profile/ecms_profile/composer.json') }}
#
#      - name: Run the development script (if not cached)
#        run: ./scripts/develop.sh
##        if: steps.lando-cache.outputs.cache-hit != 'true'
##
##      - name: Restore the lando environment from cache
##        run: |
##          cd ../develop-ecms-profile
##          lando start
##          lando drush si ecms_base --yes
##        if: steps.lando-cache.outputs.cache-hit == 'true'
#
#      - name: Check coding standards.
#        run: |
#          cd ../develop-ecms-profile
#          lando phpcs
#
#      - name: Run gulp validate.
#        run: |
#          cd ../develop-ecms-profile
#          lando gulp-distro validate
#
#      - name: Run unit tests.
#        run: |
#          cd ../develop-ecms-profile
#          pwd
#          lando phpunit --testsuite=unit
#
##      - name: Run functional tests in parallel.
##        run: |
##          cd ../develop-ecms-profile
##          lando paratest -p4 --testsuite=functional /ecms_profile
##
##      - name: Run existing tests.
##        run: |
##          cd ../develop-ecms-profile
##          lando paratest -p4 --testsuite=existing --bootstrap=/app/vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php /ecms_profile
