# Runs and tests the develop.sh script
---
name: Test deploy.sh
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: develop.sh
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment for Lando use
        run: |
          mkdir -p ~/.ssh

      - name: Install Lando
        run: |
          pushd /tmp
          wget https://files.devwithlando.io/lando-stable.deb
          sudo dpkg -i --ignore-depends=docker-ce lando-stable.deb
          popd

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run the development script
        run: ./scripts/develop.sh

      - name: Check coding standards.
        run: |
          cd ../develop-ecms-profile
          lando phpcs

      - name: Run gulp validate.
        run: |
          cd ../develop-ecms-profile
          lando gulp-distro validate

      - name: Run unit tests.
        run: |
          cd ../develop-ecms-profile
          lando phpunit --testsuite=unit

      - name: Run functional tests in parallel.
        run: |
          cd ../develop-ecms-profile
          lando paratest -p8 --testsuite=functional /ecms_profile

      - name: Run existing tests.
        run: |
          cd ../develop-ecms-profile
          lando paratest -p8 --testsuite=existing --bootstrap=/app/vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php /ecms_profile
